repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50]
      - id: check-case-conflict
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        types_or: [markdown, yaml]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.7.0"
    hooks:
      - id: nbqa-isort
        additional_dependencies: [isort]
        args: [--line-length=100, --sl]
      - id: nbqa-black
        additional_dependencies: [black]
        args: [--line-length=100]
      - id: nbqa-flake8
        additional_dependencies: [flake8]
        args: [--max-line-length=100]

  - repo: local
    hooks:
      - id: nbconvert
        name: clear notebook output
        entry: jupyter nbconvert
        language: system
        types: [jupyter]
        args: ["--clear-output", "--inplace"]
